criterions:
  PerformanceLoss:
    def_file: ./loss/SoftDiceLoss.py
    loss_params: {}
    optim_params: null
    weight: 0.2
  BCELoss:
    def_file: ./loss/BCELoss.py
    loss_params: {}
    optim_params: null
    weight: 0.8
last: false
model_dir: null
networks:
  model:
    def_file: ./models/fcn_resnet50.py
    fix: false
    optimizer: adamW
    optim_params: {lr: 0.001, momentum: 0.9, weight_decay: 0.001 }
    scheduler_params: {coslr: false, endlr: 0.0, gamma: 0.0, warmup: false, step_size: 10}
    params: {log_dir: './logs/fcn1226'}
shuffle: false
training_opt:
  phase: train
  strategy: 'keep1wsi'
  backbone: fcn-resnet50
  batch_size: 128
  datasets: HuBMAP
  display_step: 10
  display_grad: False
  display_grad_step: 10
  num_epochs: 30
  num_workers: 10
  sampler: null
  log_dir: './logs/fcn1226'
  window: 1024
  overlap: 32
  resize: 256
  transform: default
  cache_dir: /root/share/hubmap-kidney-segmentation/train/1024_32_val
val_opt:
  phase: val
  batch_size: 64
  datasets: HuBMAP
  num_workers: 12
  sampler: null
  log_dir: './logs/fcn1226/val'
  window: 1024
  overlap: 32
  resize: 256
  transform: 'val'
  cache_dir: /root/share/hubmap-kidney-segmentation/train/1024_32_val
testting_opt:
  phase: test
  batch_size: 64
  datasets: HuBMAP
  window: 1024
  overlap: 32
  resize: 256
  num_workers: 12
  transform: 'test'
  sampler: null
  cache_dir: /root/share/hubmap-kidney-segmentation/test/1024_32
  log_dir: './logs/fcn1226/test'
